# Plugins
gems:             ['jekyll-paginate', 'jekyll-gist', 'jekyll-github-metadata']

# Dependencies
# highlighter:      rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Permalinks
permalink:        pretty

# Setup
title:            BiRewire
tagline:          Efficient randomization of biological networks while preserving functional characterization of individual nodes
description:      "Efficient randomization of biological networks while preserving functional characterization of individual nodes"
#url:              https://github.com/saezlab/projectDocumentationTemplate
baseurl:          /BiRewire/
toollogo:         /BiRewire/BiRewireLogo.jpg

author:
  name:           'Andrea Gobbi [aut], Francesco Iorio [aut], Giuseppe Jurman [cbt], Davide Albanese [cbt], Julio Saez-Rodriguez [cbt]'

paginate:         5

# Custom vars
version:          1.0.1

github:
  repo:           https://github.com/saezlab/BiRewire
